unit UnitRelCar3;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QRCtrls, QuickRpt, ExtCtrls;
type
  TFormCar3=class(TForm)
    QuickRep1: TQuickRep;
    DetailBand1: TQRBand;
    QRShape1: TQRShape;
    QRShape2: TQRShape;
    QRShape3: TQRShape;
    QRShape4: TQRShape;
    QRShape5: TQRShape;
    QRShape7: TQRShape;
    QRShape8: TQRShape;
    QRShape9: TQRShape;
    QRShape10: TQRShape;
    QN1: TQRDBText;
    QN2: TQRDBText;
    QN3: TQRDBText;
    QN4: TQRDBText;
    QN5: TQRDBText;
    QN6: TQRDBText;
    QN7: TQRDBText;
    QN8: TQRDBText;
    QN9: TQRDBText;
    QN10: TQRDBText;
    QN11: TQRDBText;
    QN12: TQRDBText;
    QN13: TQRDBText;
    QN14: TQRDBText;
    QN19: TQRDBText;
    QN18: TQRDBText;
    QN17: TQRDBText;
    QN16: TQRDBText;
    QN15: TQRDBText;
    QN20: TQRDBText;
    QN21: TQRDBText;
    QN22: TQRDBText;
    QN23: TQRDBText;
    QN24: TQRDBText;
    QRShape11: TQRShape;
    QRLabel1: TQRLabel;
    QRLabel2: TQRLabel;
    QRLabel3: TQRLabel;
    QRLabel4: TQRLabel;
    QRLabel5: TQRLabel;
    PageHeaderBand1: TQRBand;
    QRShape6: TQRShape;
    QRShape12: TQRShape;
    QRShape13: TQRShape;
    QRShape14: TQRShape;
    QRShape15: TQRShape;
    QRShape16: TQRShape;
    QRShape17: TQRShape;
    QRShape18: TQRShape;
    QRShape19: TQRShape;
    RN1: TQRDBText;
    RN2: TQRDBText;
    RN3: TQRDBText;
    RN4: TQRDBText;
    RN5: TQRDBText;
    RN6: TQRDBText;
    RN7: TQRDBText;
    RN8: TQRDBText;
    RN9: TQRDBText;
    RN10: TQRDBText;
    RN11: TQRDBText;
    RN12: TQRDBText;
    RN13: TQRDBText;
    RN14: TQRDBText;
    RN19: TQRDBText;
    RN18: TQRDBText;
    RN17: TQRDBText;
    RN16: TQRDBText;
    RN15: TQRDBText;
    RN20: TQRDBText;
    RN21: TQRDBText;
    RN22: TQRDBText;
    RN23: TQRDBText;
    RN24: TQRDBText;
    QRShape20: TQRShape;
    QRLabel6: TQRLabel;
    QRLabel7: TQRLabel;
    QRLabel8: TQRLabel;
    QRLabel9: TQRLabel;
    QRLabel10: TQRLabel;
    QRShape21: TQRShape;
    QRShape22: TQRShape;
    QRShape23: TQRShape;
    QRShape24: TQRShape;
    QRShape25: TQRShape;
    QRShape26: TQRShape;
    QRShape27: TQRShape;
    QRShape28: TQRShape;
    QRShape29: TQRShape;
    SN1: TQRDBText;
    SN2: TQRDBText;
    SN3: TQRDBText;
    SN4: TQRDBText;
    SN5: TQRDBText;
    SN6: TQRDBText;
    SN7: TQRDBText;
    SN8: TQRDBText;
    SN9: TQRDBText;
    SN10: TQRDBText;
    SN11: TQRDBText;
    SN12: TQRDBText;
    SN13: TQRDBText;
    SN14: TQRDBText;
    SN19: TQRDBText;
    SN18: TQRDBText;
    SN17: TQRDBText;
    SN16: TQRDBText;
    SN15: TQRDBText;
    SN20: TQRDBText;
    SN21: TQRDBText;
    SN22: TQRDBText;
    SN23: TQRDBText;
    SN24: TQRDBText;
    QRShape30: TQRShape;
    QRLabel11: TQRLabel;
    QRLabel12: TQRLabel;
    QRLabel13: TQRLabel;
    QRLabel14: TQRLabel;
    QRLabel15: TQRLabel;
    LabelCar2: TQRLabel;
    QRDBText73: TQRDBText;
    LabelNome: TQRLabel;
    LabelEnd: TQRLabel;
    LabelFone: TQRLabel;
    QRShape31: TQRShape;
    QRShape32: TQRShape;
    QRShape33: TQRShape;
    QRShape34: TQRShape;
    QRLabel21: TQRLabel;
    ImBarra: TQRImage;
    RichText: TQRRichText;
    LabelCar1: TQRLabel;
    QRDBText1: TQRDBText;
    LP1: TQRLabel;
    LabelP1: TQRLabel;
    LP2: TQRLabel;
    LabelP2: TQRLabel;
    LP3: TQRLabel;
    LabelP3: TQRLabel;
    procedure _PROC_00588FBC(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FormCar3: TFormCar3;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFormCar3._PROC_00588FBC(Sender : TObject);
begin
(*
00588FBC   832DE833640001         sub     dword ptr [$006433E8], +$01
00588FC3   C3                     ret

*)
end;

end.