unit UnitRelCar12;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QRCtrls, QuickRpt, ExtCtrls;
type
  TFormCar12=class(TForm)
    QuickRep1: TQuickRep;
    DetailBand1: TQRBand;
    QRDBText73: TQRDBText;
    QRShape1: TQRShape;
    QRShape2: TQRShape;
    QRShape3: TQRShape;
    QRShape4: TQRShape;
    QRShape5: TQRShape;
    QRShape7: TQRShape;
    QRShape8: TQRShape;
    QRShape9: TQRShape;
    QRShape10: TQRShape;
    QN1: TQRDBText;
    QN2: TQRDBText;
    QN3: TQRDBText;
    QN4: TQRDBText;
    QN5: TQRDBText;
    QN6: TQRDBText;
    QN7: TQRDBText;
    QN8: TQRDBText;
    QN9: TQRDBText;
    QN10: TQRDBText;
    QN11: TQRDBText;
    QN12: TQRDBText;
    QN13: TQRDBText;
    QN14: TQRDBText;
    QN19: TQRDBText;
    QN18: TQRDBText;
    QN17: TQRDBText;
    QN16: TQRDBText;
    QN15: TQRDBText;
    QN20: TQRDBText;
    QN21: TQRDBText;
    QN22: TQRDBText;
    QN23: TQRDBText;
    QN24: TQRDBText;
    QRShape11: TQRShape;
    QRLabel1: TQRLabel;
    QRLabel2: TQRLabel;
    QRLabel3: TQRLabel;
    QRLabel4: TQRLabel;
    QRLabel5: TQRLabel;
    QRShape6: TQRShape;
    RichText: TQRRichText;
    procedure _PROC_005897C4(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FormCar12: TFormCar12;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFormCar12._PROC_005897C4(Sender : TObject);
begin
(*
005897C4   832DF833640001         sub     dword ptr [$006433F8], +$01
005897CB   C3                     ret

*)
end;

end.