unit UnitRelCar4a6;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QRCtrls, QuickRpt, ExtCtrls;
type
  TFormCar4a6=class(TForm)
    QuickRep1: TQuickRep;
    PageHeaderBand1: TQRBand;
    DetailBand1: TQRBand;
    LabelCar2: TQRLabel;
    QRDBText49: TQRDBText;
    LabelNome: TQRLabel;
    LabelEnd: TQRLabel;
    LabelFone: TQRLabel;
    QRShape22: TQRShape;
    ImBarra: TQRImage;
    LabelCar1: TQRLabel;
    QRDBText51: TQRDBText;
    Linha1: TQRLabel;
    Linha2: TQRLabel;
    Linha3: TQRLabel;
    Linha4: TQRLabel;
    Linha5: TQRLabel;
    Linha6: TQRLabel;
    QRLabel1: TQRLabel;
    RichText: TQRRichText;
    LP1: TQRLabel;
    LP2: TQRLabel;
    LP3: TQRLabel;
    LP4: TQRLabel;
    LP5: TQRLabel;
    LP6: TQRLabel;
    procedure QuickRep1BeforePrint(Sender : TObject);
    procedure _PROC_00589B18(Sender : TObject);
    procedure _PROC_00589B48(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FormCar4a6: TFormCar4a6;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFormCar4a6.QuickRep1BeforePrint(Sender : TObject);
begin
(*
00589AF0   55                     push    ebp
00589AF1   8BEC                   mov     ebp, esp
00589AF3   33C0                   xor     eax, eax
00589AF5   55                     push    ebp

* Possible String Reference to: 'Èê¶ÁˇÎ¯]√UãÏ3¿Uh=õX'
|
00589AF6   680F9B5800             push    $00589B0F

***** TRY
|
00589AFB   64FF30                 push    dword ptr fs:[eax]
00589AFE   648920                 mov     fs:[eax], esp
00589B01   33C0                   xor     eax, eax
00589B03   5A                     pop     edx
00589B04   59                     pop     ecx
00589B05   59                     pop     ecx
00589B06   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√UãÏ3¿Uh=õX'
|
00589B09   68169B5800             push    $00589B16
00589B0E   C3                     ret


* Reference to: System.@HandleFinally;
|
00589B0F   E990A6E7FF             jmp     004041A4
00589B14   EBF8                   jmp     00589B0E

****** END
|
00589B16   5D                     pop     ebp
00589B17   C3                     ret

*)
end;

procedure TFormCar4a6._PROC_00589B18(Sender : TObject);
begin
(*
00589B18   55                     push    ebp
00589B19   8BEC                   mov     ebp, esp
00589B1B   33C0                   xor     eax, eax
00589B1D   55                     push    ebp

* Possible String Reference to: 'Èb¶ÁˇÎ¯]√ã¿É-'
|
00589B1E   683D9B5800             push    $00589B3D

***** TRY
|
00589B23   64FF30                 push    dword ptr fs:[eax]
00589B26   648920                 mov     fs:[eax], esp
00589B29   FF0500346400           inc     dword ptr [$00643400]
00589B2F   33C0                   xor     eax, eax
00589B31   5A                     pop     edx
00589B32   59                     pop     ecx
00589B33   59                     pop     ecx
00589B34   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ã¿É-'
|
00589B37   68449B5800             push    $00589B44
00589B3C   C3                     ret


* Reference to: System.@HandleFinally;
|
00589B3D   E962A6E7FF             jmp     004041A4
00589B42   EBF8                   jmp     00589B3C

****** END
|
00589B44   5D                     pop     ebp
00589B45   C3                     ret

*)
end;

procedure TFormCar4a6._PROC_00589B48(Sender : TObject);
begin
(*
00589B48   832D0034640001         sub     dword ptr [$00643400], +$01
00589B4F   C3                     ret

*)
end;

end.