unit UnitRelCar24;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QRCtrls, QuickRpt, ExtCtrls;
type
  TFormCar24=class(TForm)
    QuickRep1: TQuickRep;
    DetailBand1: TQRBand;
    LabelCar: TQRLabel;
    NumCar: TQRDBText;
    PageHeaderBand1: TQRBand;
    C11: TQRDBText;
    C12: TQRDBText;
    C13: TQRDBText;
    C14: TQRDBText;
    C15: TQRDBText;
    C16: TQRDBText;
    C17: TQRDBText;
    C18: TQRDBText;
    C19: TQRDBText;
    C110: TQRDBText;
    C111: TQRDBText;
    C112: TQRDBText;
    C114: TQRDBText;
    C115: TQRDBText;
    C120: TQRDBText;
    C119: TQRDBText;
    C118: TQRDBText;
    C117: TQRDBText;
    C116: TQRDBText;
    C121: TQRDBText;
    C122: TQRDBText;
    C123: TQRDBText;
    C124: TQRDBText;
    C113: TQRDBText;
    ImB1: TQRImage;
    procedure FormActivate(Sender : TObject);
    procedure _PROC_0062B9C8(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FormCar24: TFormCar24;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFormCar24.FormActivate(Sender : TObject);
begin
(*
0062B994   C3                     ret

*)
end;

procedure TFormCar24._PROC_0062B9C8(Sender : TObject);
begin
(*
0062B9C8   832D9CB36A0001         sub     dword ptr [$006AB39C], +$01
0062B9CF   C3                     ret

*)
end;

end.