unit UnitRelCar2;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QRCtrls, QuickRpt, ExtCtrls;
type
  TFormCar2=class(TForm)
    QuickRep1: TQuickRep;
    DetailBand1: TQRBand;
    PageHeaderBand1: TQRBand;
    LabelCar2: TQRLabel;
    QRDBText49: TQRDBText;
    LabelNome: TQRLabel;
    LabelEnd: TQRLabel;
    LabelFone: TQRLabel;
    QRShape22: TQRShape;
    QRShape1: TQRShape;
    QRShape2: TQRShape;
    QRShape3: TQRShape;
    QRShape4: TQRShape;
    QRShape5: TQRShape;
    QRShape7: TQRShape;
    QRShape8: TQRShape;
    QRShape9: TQRShape;
    QRShape10: TQRShape;
    QN1: TQRDBText;
    QN2: TQRDBText;
    QN3: TQRDBText;
    QN4: TQRDBText;
    QN5: TQRDBText;
    QN6: TQRDBText;
    QN7: TQRDBText;
    QN8: TQRDBText;
    QN9: TQRDBText;
    QN10: TQRDBText;
    QN11: TQRDBText;
    QN12: TQRDBText;
    QN13: TQRDBText;
    QN14: TQRDBText;
    QN19: TQRDBText;
    QN18: TQRDBText;
    QN17: TQRDBText;
    QN16: TQRDBText;
    QN15: TQRDBText;
    QN20: TQRDBText;
    QN21: TQRDBText;
    QN22: TQRDBText;
    QN23: TQRDBText;
    QN24: TQRDBText;
    QRShape11: TQRShape;
    QRLabel1: TQRLabel;
    QRLabel2: TQRLabel;
    QRLabel3: TQRLabel;
    QRLabel4: TQRLabel;
    QRLabel5: TQRLabel;
    QRShape6: TQRShape;
    QRShape12: TQRShape;
    QRShape13: TQRShape;
    QRShape14: TQRShape;
    QRShape15: TQRShape;
    QRShape16: TQRShape;
    QRShape17: TQRShape;
    QRShape18: TQRShape;
    QRShape19: TQRShape;
    RN1: TQRDBText;
    RN2: TQRDBText;
    RN3: TQRDBText;
    RN4: TQRDBText;
    RN5: TQRDBText;
    RN6: TQRDBText;
    RN7: TQRDBText;
    RN8: TQRDBText;
    RN9: TQRDBText;
    RN10: TQRDBText;
    RN11: TQRDBText;
    RN12: TQRDBText;
    RN13: TQRDBText;
    RN14: TQRDBText;
    RN19: TQRDBText;
    RN18: TQRDBText;
    RN17: TQRDBText;
    RN16: TQRDBText;
    RN15: TQRDBText;
    RN20: TQRDBText;
    RN21: TQRDBText;
    RN22: TQRDBText;
    RN23: TQRDBText;
    RN24: TQRDBText;
    QRShape20: TQRShape;
    QRLabel6: TQRLabel;
    QRLabel7: TQRLabel;
    QRLabel8: TQRLabel;
    QRLabel9: TQRLabel;
    QRLabel10: TQRLabel;
    QRShape32: TQRShape;
    QRShape34: TQRShape;
    LabelCar1: TQRLabel;
    QRDBText51: TQRDBText;
    QRLabel12: TQRLabel;
    ImBarra: TQRImage;
    RichText: TQRRichText;
    LP1: TQRLabel;
    LabelP1: TQRLabel;
    LP2: TQRLabel;
    LabelP2: TQRLabel;
    procedure _PROC_005886D8(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FormCar2: TFormCar2;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFormCar2._PROC_005886D8(Sender : TObject);
begin
(*
005886D8   832DE033640001         sub     dword ptr [$006433E0], +$01
005886DF   C3                     ret

*)
end;

end.